version: '3'
services:
  dockerlamp:
    build: ./LAMP
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
      - 443:443
      - 3306:3306

  githook_installer:
    build: ./hookinstaller
    volumes:
      - ./hookinstaller/hooks:/tmp/hooks
      - ./.git/hooks:/tmp/proj

  toolbox:
    build: ./toolbox
    volumes:
      - .:/mnt/src
    command: /sbin/init

  phan:
    image: cloudflare/phan
    volumes:
      - .:/mnt/src:cached
    entrypoint: []
    command: sh -c "cd /mnt/src && /opt/phan/phan -xpo analysis.txt --color"

