version: '3'
services:
  dockerlamp:
    build: ./LAMP
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
      - 443:443
  
  dbserver:
    image: mysql:5.7
    ports:
      - 3306:3306
    hostname: dbserver
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: lftv
      MYSQL_PASSWORD: password
    volumes:
      - db_local_data:/var/lib/mysql

  githook_installer:
    build: ./hookinstaller
    volumes:
      - ./hookinstaller/hooks:/tmp/hooks
      - ./.git/hooks:/tmp/proj

  toolbox:
    build: ./toolbox
    volumes:
      - .:/mnt/src
    command: /sbin/init

  phan:
    image: cloudflare/phan
    volumes:
      - .:/mnt/src:cached
    entrypoint: []
    command: sh -c "cd /mnt/src && /opt/phan/phan -xpo analysis.txt --color"
volumes:
  db_local_data:
    driver: local

