version: '3'
services:
  dockerlamp:
    build: ./LAMP
    volumes:
      - ./:/var/www/html

  githook_installer:
    build: ./hookinstaller
    volumes:
      - ./hookinstaller/hooks:/tmp/hooks
      - ./.git/hooks:/tmp/proj

  phan:
    image: cloudflare/phan
    volumes:
      - .:/mnt/src:cached
    entrypoint: []
    command: sh -c "cd /mnt/src && /opt/phan/phan -xpo analysis.txt --color"
