#!/bin/bash
wget http://xdebug.org/files/xdebug-2.6.0.tgz
tar -xzpvf xdebug-2.6.0.tgz
cd xdebug-2.6.0
phpize
./configure
make && \
cp modules/xdebug.so /usr/local/lib/php/extensions/no-debug-non-zts-20170718 && \
echo "zend_extension = /usr/local/lib/php/extensions/no-debug-non-zts-20170718/xdebug.so" >> /usr/local/lib/php.ini
